/*
 * generated by Xtext
 */
package xgen.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GrammarUiModule extends xgen.ui.AbstractGrammarUiModule {
	public GrammarUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
