/**
 * generated by Xtext
 */
package xgen.serializer;

import xgen.serializer.AbstractGrammarSemanticSequencer;

@SuppressWarnings("all")
public class GrammarSemanticSequencer extends AbstractGrammarSemanticSequencer {
}
