/**
 * generated by Xtext
 */
package xgen.serializer;

import xgen.serializer.AbstractGrammarSyntacticSequencer;

@SuppressWarnings("all")
public class GrammarSyntacticSequencer extends AbstractGrammarSyntacticSequencer {
}
