/**
 * generated by Xtext
 */
package xgen.generator;

import com.google.common.base.Objects;
import xgen.parsetree.Leaf;
import xgen.postprocess.RemoveAll;

@SuppressWarnings("all")
public class RemoveRemainingInitial extends RemoveAll {
  protected boolean candidate(final Leaf it) {
    boolean _equals = Objects.equal(it.value, "<initial>");
    return _equals;
  }
}
