/**
 * generated by Xtext
 */
package xgen.generator;

import com.google.common.base.Objects;
import java.util.Collection;
import xgen.parsetree.Leaf;
import xgen.postprocess.TransformAll;

@SuppressWarnings("all")
public class ReplaceStateName extends TransformAll {
  private int i = 0;
  
  private final Collection<String> exchange;
  
  public ReplaceStateName(final Collection<String> exchange) {
    this.exchange = exchange;
  }
  
  protected void resetOne() {
    this.i = 0;
    this.exchange.clear();
  }
  
  protected Leaf transform(final Leaf it) {
    boolean _notEquals = (!Objects.equal(it.value, "<state name>"));
    if (_notEquals) {
      return it;
    }
    final String r = ("State" + Integer.valueOf(this.i));
    int _plus = (this.i + 1);
    this.i = _plus;
    this.exchange.add(r);
    Leaf _leaf = new Leaf(r);
    return _leaf;
  }
}
