/**
 * generated by Xtext
 */
package xgen.generator;

import com.google.common.base.Objects;
import xgen.parsetree.Leaf;
import xgen.postprocess.ReplaceOne;

@SuppressWarnings("all")
public class ReplaceInitial extends ReplaceOne {
  protected boolean candidate(final Leaf it) {
    boolean _equals = Objects.equal(it.value, "<INITIAL>");
    return _equals;
  }
  
  protected Leaf replace(final Leaf it) {
    Leaf _leaf = new Leaf("initial");
    return _leaf;
  }
}
