/*
 * generated by Xtext
 */
package xgen.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import xgen.ui.internal.ApplicationActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ApplicationExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ApplicationActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ApplicationActivator.getInstance().getInjector(ApplicationActivator.XGEN_APPLICATION);
	}
	
}
