/*
* generated by Xtext
*/
package xgen;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ApplicationUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return xgen.ui.internal.ApplicationActivator.getInstance().getInjector("xgen.Application");
	}
	
}
