/*
* generated by Xtext
*/
package xgen.parser.antlr;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import xgen.services.ApplicationGrammarAccess;

import com.google.inject.Inject;

public class ApplicationParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ApplicationGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected xgen.parser.antlr.internal.InternalApplicationParser createParser(XtextTokenStream stream) {
		return new xgen.parser.antlr.internal.InternalApplicationParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public ApplicationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ApplicationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
