/*
* generated by Xtext
*/
package xgen;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ApplicationStandaloneSetup extends ApplicationStandaloneSetupGenerated{

	public static void doSetup() {
		new ApplicationStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

