/*
 * generated by Xtext
 */
package xgen.validation;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractApplicationValidator extends xgen.validation.GrammarValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(xgen.application.ApplicationPackage.eINSTANCE);
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://xgen/Grammar/1.0"));
		return result;
	}
}
