/*
 * generated by Xtext
 */
package xgen.ui.contentassist

import xgen.ui.contentassist.AbstractGrammarProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class GrammarProposalProvider extends AbstractGrammarProposalProvider {
}
