/*
* generated by Xtext
*/
package xgen;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class GrammarStandaloneSetup extends GrammarStandaloneSetupGenerated{

	public static void doSetup() {
		new GrammarStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

