/*
 * generated by Xtext
 */
package xgen.generator

import org.eclipse.xtext.generator.IFileSystemAccess
import org.eclipse.xtext.generator.IGenerator
import org.eclipse.emf.ecore.resource.Resource

/**
 * Generates code from your model files on save.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#TutorialCodeGeneration
 */
class GrammarGenerator implements IGenerator {

	override void doGenerate(Resource resource, IFileSystemAccess fsa) {
	}
}
