/*
 * generated by Xtext
 */
package xgen.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ApplicationUiModule extends xgen.ui.AbstractApplicationUiModule {
	public ApplicationUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
