/*
* generated by Xtext
*/
package xgen.parser.antlr;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import xgen.services.GrammarGrammarAccess;

import com.google.inject.Inject;

public class GrammarParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private GrammarGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected xgen.parser.antlr.internal.InternalGrammarParser createParser(XtextTokenStream stream) {
		return new xgen.parser.antlr.internal.InternalGrammarParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Grammar";
	}
	
	public GrammarGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GrammarGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
