/*
* generated by Xtext
*/
package xgen.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import xgen.services.ApplicationGrammarAccess;

public class ApplicationParser extends AbstractContentAssistParser {
	
	@Inject
	private ApplicationGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected xgen.ui.contentassist.antlr.internal.InternalApplicationParser createParser() {
		xgen.ui.contentassist.antlr.internal.InternalApplicationParser result = new xgen.ui.contentassist.antlr.internal.InternalApplicationParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getApplyAccess().getAlternatives_7_1(), "rule__Apply__Alternatives_7_1");
					put(grammarAccess.getConstruct2Access().getAlternatives(), "rule__Construct2__Alternatives");
					put(grammarAccess.getConstruct4Access().getAlternatives(), "rule__Construct4__Alternatives");
					put(grammarAccess.getApplyAccess().getGroup(), "rule__Apply__Group__0");
					put(grammarAccess.getApplyAccess().getGroup_7(), "rule__Apply__Group_7__0");
					put(grammarAccess.getCallReplacementAccess().getGroup(), "rule__CallReplacement__Group__0");
					put(grammarAccess.getCallReplacementAccess().getGroup_2(), "rule__CallReplacement__Group_2__0");
					put(grammarAccess.getRuleReplacementAccess().getGroup(), "rule__RuleReplacement__Group__0");
					put(grammarAccess.getQIDAccess().getGroup(), "rule__QID__Group__0");
					put(grammarAccess.getQIDAccess().getGroup_1(), "rule__QID__Group_1__0");
					put(grammarAccess.getGrammarAccess().getGroup(), "rule__Grammar__Group__0");
					put(grammarAccess.getDefinitionAccess().getGroup(), "rule__Definition__Group__0");
					put(grammarAccess.getConstruct0Access().getGroup(), "rule__Construct0__Group__0");
					put(grammarAccess.getConstruct0Access().getGroup_1(), "rule__Construct0__Group_1__0");
					put(grammarAccess.getConstruct0Access().getGroup_1_3(), "rule__Construct0__Group_1_3__0");
					put(grammarAccess.getConstruct1Access().getGroup(), "rule__Construct1__Group__0");
					put(grammarAccess.getConstruct1Access().getGroup_1(), "rule__Construct1__Group_1__0");
					put(grammarAccess.getConstruct2Access().getGroup_0(), "rule__Construct2__Group_0__0");
					put(grammarAccess.getConstruct2Access().getGroup_1(), "rule__Construct2__Group_1__0");
					put(grammarAccess.getConstruct3Access().getGroup(), "rule__Construct3__Group__0");
					put(grammarAccess.getConstruct3Access().getGroup_1(), "rule__Construct3__Group_1__0");
					put(grammarAccess.getConstruct3Access().getGroup_1_3(), "rule__Construct3__Group_1_3__0");
					put(grammarAccess.getConstruct4Access().getGroup_0(), "rule__Construct4__Group_0__0");
					put(grammarAccess.getConstruct4Access().getGroup_1(), "rule__Construct4__Group_1__0");
					put(grammarAccess.getConstruct4Access().getGroup_2(), "rule__Construct4__Group_2__0");
					put(grammarAccess.getConstruct4Access().getGroup_3(), "rule__Construct4__Group_3__0");
					put(grammarAccess.getConstruct4Access().getGroup_4(), "rule__Construct4__Group_4__0");
					put(grammarAccess.getModelAccess().getApplicationsAssignment(), "rule__Model__ApplicationsAssignment");
					put(grammarAccess.getApplyAccess().getTargetAssignment_1(), "rule__Apply__TargetAssignment_1");
					put(grammarAccess.getApplyAccess().getMinAssignment_3(), "rule__Apply__MinAssignment_3");
					put(grammarAccess.getApplyAccess().getMaxAssignment_5(), "rule__Apply__MaxAssignment_5");
					put(grammarAccess.getApplyAccess().getCallReplacementsAssignment_7_1_0(), "rule__Apply__CallReplacementsAssignment_7_1_0");
					put(grammarAccess.getApplyAccess().getRuleReplacementsAssignment_7_1_1(), "rule__Apply__RuleReplacementsAssignment_7_1_1");
					put(grammarAccess.getCallReplacementAccess().getSelectorAssignment_1(), "rule__CallReplacement__SelectorAssignment_1");
					put(grammarAccess.getCallReplacementAccess().getPositionedAssignment_2_0(), "rule__CallReplacement__PositionedAssignment_2_0");
					put(grammarAccess.getCallReplacementAccess().getPositionAssignment_2_1(), "rule__CallReplacement__PositionAssignment_2_1");
					put(grammarAccess.getCallReplacementAccess().getTargetAssignment_4(), "rule__CallReplacement__TargetAssignment_4");
					put(grammarAccess.getCallReplacementAccess().getReplacementAssignment_6(), "rule__CallReplacement__ReplacementAssignment_6");
					put(grammarAccess.getRuleReplacementAccess().getTargetAssignment_1(), "rule__RuleReplacement__TargetAssignment_1");
					put(grammarAccess.getRuleReplacementAccess().getReplacementAssignment_3(), "rule__RuleReplacement__ReplacementAssignment_3");
					put(grammarAccess.getGrammarAccess().getDefinitionsAssignment_1(), "rule__Grammar__DefinitionsAssignment_1");
					put(grammarAccess.getDefinitionAccess().getLexicalAssignment_1(), "rule__Definition__LexicalAssignment_1");
					put(grammarAccess.getDefinitionAccess().getNameAssignment_2(), "rule__Definition__NameAssignment_2");
					put(grammarAccess.getDefinitionAccess().getRhsAssignment_4(), "rule__Definition__RhsAssignment_4");
					put(grammarAccess.getConstruct0Access().getOperandsAssignment_1_2(), "rule__Construct0__OperandsAssignment_1_2");
					put(grammarAccess.getConstruct0Access().getOperandsAssignment_1_3_1(), "rule__Construct0__OperandsAssignment_1_3_1");
					put(grammarAccess.getConstruct1Access().getOperandsAssignment_1_1(), "rule__Construct1__OperandsAssignment_1_1");
					put(grammarAccess.getConstruct1Access().getOperandsAssignment_1_2(), "rule__Construct1__OperandsAssignment_1_2");
					put(grammarAccess.getConstruct2Access().getOperandAssignment_0_2(), "rule__Construct2__OperandAssignment_0_2");
					put(grammarAccess.getConstruct2Access().getOperandAssignment_1_2(), "rule__Construct2__OperandAssignment_1_2");
					put(grammarAccess.getConstruct3Access().getMinAssignment_1_2(), "rule__Construct3__MinAssignment_1_2");
					put(grammarAccess.getConstruct3Access().getUpperBoundedAssignment_1_3_0(), "rule__Construct3__UpperBoundedAssignment_1_3_0");
					put(grammarAccess.getConstruct3Access().getMaxAssignment_1_3_1(), "rule__Construct3__MaxAssignment_1_3_1");
					put(grammarAccess.getConstruct4Access().getMinAssignment_0_1(), "rule__Construct4__MinAssignment_0_1");
					put(grammarAccess.getConstruct4Access().getMaxAssignment_0_3(), "rule__Construct4__MaxAssignment_0_3");
					put(grammarAccess.getConstruct4Access().getValueAssignment_1_1(), "rule__Construct4__ValueAssignment_1_1");
					put(grammarAccess.getConstruct4Access().getTargetAssignment_3_1(), "rule__Construct4__TargetAssignment_3_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			xgen.ui.contentassist.antlr.internal.InternalApplicationParser typedParser = (xgen.ui.contentassist.antlr.internal.InternalApplicationParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public ApplicationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ApplicationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
