/*
 * generated by Xtext
 */
package xgen.validation

import xgen.application.Apply
import xgen.application.ApplicationPackage
import org.eclipse.xtext.validation.Check

//import org.eclipse.xtext.validation.Check
/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class ApplicationValidator extends AbstractApplicationValidator {

	@Check
	def checkZeroToOnePostprocessor(Apply a) {
		if (!#[0, 1].contains(a.postProcessors.size))
			error('At most one post processor allowed for now', ApplicationPackage.Literals.APPLY__POST_PROCESSORS)
	}
}
