/*
 * generated by Xtext
 */
package xgen.validation

import org.eclipse.xtext.validation.Check
import xgen.grammar.Range
import xgen.grammar.GrammarPackage

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class GrammarValidator extends AbstractGrammarValidator {
	@Check
	def checkRangeUpward(Range x) {
		if (x.min > x.max)
			error('End of range must be greater or equal to the start', GrammarPackage.Literals.RANGE__MAX)
	}
}
