/*
 * generated by Xtext
 */
package xgen.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import xgen.ui.internal.GrammarActivator;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GrammarExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GrammarActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GrammarActivator.getInstance().getInjector(GrammarActivator.XGEN_GRAMMAR);
	}
	
}
