/**
 * generated by Xtext
 */
package xgen.validation;

import org.eclipse.xtext.validation.Check;
import xgen.grammar.GrammarPackage.Literals;
import xgen.grammar.Range;
import xgen.validation.AbstractGrammarValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class GrammarValidator extends AbstractGrammarValidator {
  @Check
  public void checkRangeUpward(final Range x) {
    char _min = x.getMin();
    char _max = x.getMax();
    boolean _greaterThan = (_min > _max);
    if (_greaterThan) {
      this.error("End of range must be greater or equal to the start", Literals.RANGE__MAX);
    }
  }
}
